kafka:
    bootstrapAddress: 172.18.0.1:9092
    topic:
        customer: customer
        order: order
    group:
        market: market
        financial: financial

schema:
    registry:
        url: 172.18.0.1:8080